// Buscar todos pokemon, com paginação. Se não passar offset tem 1 como fixo
GET http://localhost:3003/page/poke
Content-Type: application/json

{
    "offset": 2
}

// Buscar todos pokemon com um type especifico
###
GET http://localhost:3003/type
Content-Type: application/json

{
    "type":"POISON"
}

// Buscar todos pokemon sem filtro somente dados completos para verificação de comandos anteriores
###
GET http://localhost:3003/pokemon

###

// Buscar todos pokemon com 2 types (type_1 e type_2 da tabela) paginando com limite de 10 por page
// senão for passado algum type ira retornar aquele que possiu tabela vazia(alguns dados tem type_1 ou type_2 vazios)
// offset podendo ser passado, senão tem fixo como os 10 primeiros
GET http://localhost:3003/page/poke/types
Content-Type: application/json

{
    "type1":"BUG",
    "type2":"Poison",
    "offset": 2
}

###
GET http://localhost:3003/name
Content-Type: application/json

{
    "name": "cam"
}